CREATE DATABASE IF NOT EXISTS YAJO;
USE YAJO;
CREATE TABLE IF NOT EXISTS Users(
	UserID INT,
    UserName VARCHAR(50),
    UserEmail VARCHAR(500),
    UserPassword VARCHAR(500),
    UserVerfited TINYINT(1),
    UserSigninDate TIMESTAMP,
    UserPremmission VARCHAR(50),
    PRIMARY KEY(UserID)
);
CREATE TABLE IF NOT EXISTS Catagorys(
	CatagoryID INT NOT NULL,
    CatagoryName VARCHAR(100) NOT NULL,
    PRIMARY KEY(CatagoryID)
);
CREATE TABLE IF NOT EXISTS Posts(
	PostID INT,
    PostImage VARCHAR(50) NOT NULL,
    PostText TEXT NOT NULL,
    UserID INT NOT NULL,
    CatagoryID INT,
    PRIMARY KEY(PostID),
    FOREIGN KEY(CatagoryID) REFERENCES Catagorys(CatagoryID),
    FOREIGN KEY(UserID) REFERENCES Users(UserID)
);
CREATE TABLE IF NOT EXISTS Reviews(
	ReviewID INT NOT NULL,
    ReviewContent TEXT NOT NULL,
    ReviewRating FLOAT NOT NULL,
    ReviewDate TIMESTAMP NOT NULL,
    UserID INT NOT NULL,
    PostID INT NOT NULL,
    PRIMARY KEY(ReviewID),
    FOREIGN KEY(UserID) REFERENCES Users(UserID),
    FOREIGN KEY(PostID) REFERENCES Posts(PostID)
);